import sys
import os
import csv
import matplotlib.pyplot as plt

def parse_log(log_path):
	"""
	Parses the TSV log file generated by the advanced_client.
	Returns lists of relative request times, latencies, and response sizes.
	"""
	req_times = []
	latencies = []
	response_sizes = []

	try:
		with open(log_path, 'r', encoding='utf-8') as f:
			reader = csv.reader(f, delimiter='\t')
			for row in reader:
				# Expecting: domain, time_req, time_recv, response_size
				if len(row) < 4:
					continue
				
				try:
					t_req = float(row[1])
					t_recv = float(row[2])
					if row[3].isdigit():
						size_bytes = int(row[3])
					else:
						size_bytes = 0 # Handle "ERROR" strings safely
						
				except ValueError:
					continue # Skip malformed rows
				
				latency = t_recv - t_req
				
				req_times.append(t_req)
				latencies.append(latency)
				response_sizes.append(size_bytes)
				
	except FileNotFoundError:
		print(f"[!] Error: Log file not found at {log_path}")
		sys.exit(1)

	return req_times, latencies, response_sizes

def main():
	# Strictly enforce the 4 arguments specified in the assignment
	if len(sys.argv) != 5:
		print("Usage: python grapher.py [network_scenario_path] [client_query_profile_path] [log_path] [output_graph_path]")
		sys.exit(1)

	network_scenario_path = sys.argv[1]
	client_query_profile_path = sys.argv[2]
	log_path = sys.argv[3]
	output_graph_path = sys.argv[4]

	print(f"[*] Parsing log file: {log_path}")
	req_times, latencies, response_sizes = parse_log(log_path)

	if not req_times:
		print("[!] No valid data found in the log file.")
		sys.exit(1)

	# Normalize timestamps so the graph starts at T=0
	start_time = min(req_times)
	rel_times = [t - start_time for t in req_times]

	# Create the output directory if it doesn't exist
	out_dir = os.path.dirname(output_graph_path)
	if out_dir and not os.path.exists(out_dir):
		os.makedirs(out_dir)

	print(f"[*] Generating plots with {len(rel_times)} data points...")

	# Set up a two-panel plot (Latency on top, Quality/Size on bottom)
	fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
	fig.suptitle('Proxy Congestion Management Performance', fontsize=16)

	# Subplot 1: Latency (Delay)
	ax1.scatter(rel_times, latencies, color='crimson', alpha=0.7, edgecolors='k', s=40)
	ax1.set_ylabel('Request Latency (seconds)', fontsize=12)
	ax1.set_title('Delay per Request', fontsize=10)
	ax1.grid(True, linestyle='--', alpha=0.6)

	# Subplot 2: Quality (Response Size)
	ax2.scatter(rel_times, response_sizes, color='dodgerblue', alpha=0.7, edgecolors='k', s=40)
	ax2.set_xlabel('Time Elapsed (seconds)', fontsize=12)
	ax2.set_ylabel('Response Size (bytes)', fontsize=12)
	ax2.set_title('File Quality Delivered (Higher is Better)', fontsize=10)
	ax2.grid(True, linestyle='--', alpha=0.6)

	# Add scenario info to the bottom of the graph for reference
	scenario_text = f"Network: {os.path.basename(network_scenario_path)} | Profile: {os.path.basename(client_query_profile_path)}"
	fig.text(0.5, 0.02, scenario_text, ha='center', fontsize=9, style='italic')

	# Save and cleanup
	plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to fit the text at the bottom
	plt.savefig(output_graph_path, format='pdf')
	plt.close()

	print(f"[*] Success! Graph saved to: {output_graph_path}")

if __name__ == "__main__":
	main()